### ISSUE TITLE
Add MacOS Build

### ISSUE THREAD

**Issue by elliottnichols** [arkiaconsulting/terraform-provider-akc#12]
Please add support for darwin_amd64 arch.

**Comment by mattmichal** [comment]
Adding support for this as I have several team members on Macs that cannot init locally. I see that there was a comment on PR #11; will support be added there or in a separate one?

**Comment by kbrady-servian** [comment]
fyi - it works inside a debian container with a volume mount:

`docker run --rm -it -v $(pwd):/tmp --name debian debian`

$pwd has my terraform with the provider

**Comment by arkiaman** [comment]
fixed in v0.3.0
