### ISSUE TITLE
Cannot make the data source working

### ISSUE THREAD

**Issue by czmirek** [arkiaconsulting/terraform-provider-akc#13]
Terraform v0.14.6
+ provider registry.terraform.io/arkiaconsulting/akc v0.2.1
+ provider registry.terraform.io/hashicorp/azurerm v2.47.0

The data key vaule source does not work :(
When you run terraform plan, the following error is produced.

```
Error: Error getting App Configuration key %00/test: Unexpected error (Forbidden)
```

Single terraform file project.
```
terraform {
  required_providers {
    azurerm = {
        source = "hashicorp/azurerm"
        version = ">= 2.26"
    }
    akc = {
      source = "arkiaconsulting/akc"
    }
  }
}
provider "azurerm" {
    skip_provider_registration = true
    features {}
}
data "azurerm_app_configuration" "appconf" {
  name                = "app-dev-ac"
  resource_group_name = "devops-dev-rg"
}

data "akc_key_value" "application_id" {
  endpoint = data.azurerm_app_configuration.appconf.endpoint
  key      = "test"
}
```

**Comment by arkiaman** [comment]
@czmirek are you sure that the identity under which terraform is executed, has at least the RBAC role App Configuration Data Reader ? The assignment can sometime take several minutes to be effectively applied.

**Comment by czmirek** [comment]
@arkiaconsulting Thank you for responding to this :)

I'm running terraform in powershell with az login set to my user account which has full ownership over the resource group where app configuration is.

Or is your module supposed to be running strictly under service principal, it cannot run with user pricnipal?

**Comment by arkiaman** [comment]
Being Owner or Contributor is not sufficient. You must be App Configuration Data Reader (or Owner) (and wait some minutes)

**Comment by czmirek** [comment]
Oh I didn't realize this had to be set because `az appconfig` commands worked for me without any issues in the same terminal. Well our administrator who handles subscription permissions is already off so I'll write tomorrow if that worked.

**Comment by czmirek** [comment]
Our admin gave me the `App Configuration Data Owner` permission and it works now. Thank you for responding! Closing the issue :)
