### ISSUE TITLE
Error with Applying

### ISSUE THREAD

**Issue by wizarden1** [arkiaconsulting/terraform-provider-akc#17]
Error: Unexpected error (Forbidden)

  on main.tf line 60, in resource "akc_key_value" "rg_name":
  60: resource "akc_key_value" "rg_name" {

I can confirm that I encountered Forbidden though I am owner and contributor to the target subscription. What fixed it for me was explicitly adding myself as App Configuration Data Owner to the subscription, and waiting ~10 minutes before applying again. The documentation states App Configuration Data Owner is required, but I assumed that because I was subscription owner I wouldn't need it explicitly.

https://www.gitmemory.com/issue/arkiaconsulting/terraform-provider-akc/3/753067706

With  azure cli I can add data without adding myself to App Configuration Data Owner to that resource

**Comment by arkiaman** [comment]
I can confirm that the permission `App Configuration Data Owner` is required, even if you are owner of the subscription. There is a difference in RBAC between control plane and data plane. This is also the case, for example, in the Key Vault resource, where you would need to be `Key Vault Secret Officer`(for example).
