### ISSUE TITLE
Feature resource

### ISSUE THREAD

**Issue by wizarden1** [arkiaconsulting/terraform-provider-akc#18]
Request for resource for create features.

**Comment by arkiaman** [comment]
I'm not sure to invest mush more on this provider, as the azurerm team is working on it, although we didn't hear from it since 6 months...

**Comment by arkiaman** [comment]
@wizarden1 I'm working on the support of the features. I'm wondering how to handle the `enabled` state. Some would use features by manually triggering them (eg. from the portal), and others would use features by relying only on their terraform configuration (ie, to change the state of the feature, apply the terraform configuration).

I've started to implement this by using a `initially_enabled` terraform attribute.

What's your idea about this ?

**Comment by wizarden1** [comment]
Hi

You can use just enabled or status
And terraform has lifecycle ignore for that purpose

**Comment by arkiaman** [comment]
Resolved in v1.1.0
