### ISSUE TITLE
Creating akc_key_value Forbidden

### ISSUE THREAD

**Issue by Mimetis** [arkiaconsulting/terraform-provider-akc#3]
Hello 

Still have an issue when trying to create key / value entry
Here is a sample, extract from my whole project, that reproduce my issue:

``` 
terraform {
  required_providers {
    akc = {
      source = "arkiaconsulting/akc"
    }
  }
}

provider "azurerm" {
  version = "=2.27.0"
  features {}
}

provider "akc" {
}

# ---------------------------------------------------------

data "azurerm_client_config" "current" {}

# ---------------------------------------------------------

variable rg_prefix {
  default     = "rg_appconf"
}
variable rg_location {
  default     = "northeurope"
}
variable environment {
  default     = "dev"
}

# ---------------------------------------------------------
resource "random_string" "unique" {
  length  = 4
  special = false
  upper   = false
  number  = false
}

resource "azurerm_resource_group" "rg" {
  name     = "${var.rg_prefix}-${var.environment}"
  location = var.rg_location
  tags = {
    environment = var.environment
  }

  lifecycle {
    ignore_changes = [
      tags
    ]
  }
}

resource "azurerm_app_configuration" "app_conf"{
  name                = "conf${var.environment}${random_string.unique.result}"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  sku                 = "standard"

  lifecycle {
    ignore_changes = [
      tags
    ]
  }
}

# ---------------------------------------------------------

resource "azurerm_role_assignment" "app_conf_contributor_2" {
  scope                = azurerm_app_configuration.app_conf.id
  role_definition_name = "App Configuration Data Owner"
  principal_id         = data.azurerm_client_config.current.object_id
}

# ---------------------------------------------------------

resource "akc_key_value" "rg_name" {
  endpoint = azurerm_app_configuration.app_conf.endpoint
  key      = "rg_name"
  value    = azurerm_resource_group.rg.name
}

```

Unfortunately, the error raised is not really verbose:

``` bash
akc_key_value.rg_name: Creating...

Error: Unexpected error (Forbidden)

  on main.tf line 60, in resource "akc_key_value" "rg_name":
  60: resource "akc_key_value" "rg_name" {
```

Obviously, I'm the owner of the subscription, and i'm able to create an entry from the azure portal.

**Comment by arkiaman** [comment]
@Mimetis When running your terraform command, do you use your own user identity or a service principal ?

**Comment by Mimetis** [comment]
My own identity:

``` bash
$ az account list
[
  {
    "cloudName": "AzureCloud",
    "homeTenantId": "72f988bf-xxxxx",
    "id": "6d854ccd-xxxxx",
    "isDefault": true,
    "managedByTenants": [
    ],
    "name": "Interne spertus",
    "state": "Enabled",
    "tenantId": "72f988bf-xxxxx",
    "user": {
      "name": "spertus@microsoft.com",
      "type": "user"
    }
  },
```
In my real project, everything is running under a SPN, but obviously, I've set the required authorization for this SPN.
Anyway, even with this simple tf script, using my own account, it does not work.
I'm trying to look into your code, but you may be faster than me 👍

**Comment by arkiaman** [comment]
I'll look at the code, but to be honest, I think that there's an authorization issue on your side. I've been using this provider in production for several months without any issue...

**Comment by Mimetis** [comment]
I'am able to create everything else, resource group, key vault, cosmos db, app services and so on...
On first impressions, it seems it's coming from my side, but honestly, I can't see why it's working for everything else and not for the akc_key_value

Still looking at your code, and I see your using the azure auth provider, using the `NewAuthorizerFromCLIWithResource` method.
Seems there is another method called `NewAuthorizerFromCLI`.
Since I'm not very aware of what is the differences between these two methods, do you think it could come from that ?

https://github.com/Azure/go-autorest/blob/0529470822b50a15b3b5512b68bc2ff076e7d691/autorest/azure/auth/auth.go#L263-L289

**Comment by Mimetis** [comment]
Looking at the code from azure auth, the `NewAuthorizerFromCLI` method requests an Azure AD token for resource `https://management.azure.com/`, that make totally sense for me.

On your side, you are requesting a token for the resource endpoint (something like `https://confdevqtno.azconfig.io`) 
I don't understand this. 
I've worked a lot with Azure AD, I may be wrong, but it seems to me that getting an Azure AD token from a resource endpoint, is not a good thing :)
But once again, just trying to understand, not sure I'm right on this one.

**Comment by arkiaman** [comment]
`NewAuthorizerFromCLIWithResource` is the right method to be used, otherwise you get a token which audience is dedicated to the AzureRM Api, that we don't want as the right audience is the App Configuration Api. See [here](https://stackoverflow.com/a/61899608/1303737) and [here](https://github.com/Azure/AppConfiguration/blob/main/docs/REST/authentication/aad.md)

Are you sure that you're logged in to the CLI with the right identity ? `az account show`

**Comment by Mimetis** [comment]
Yes, I'm on the right subscription, with right identity.

Still investigating a little bit..

**Comment by Mimetis** [comment]
Just made the test in another tenant, in another subscription in another company, and it worked fine.
So seems I miss something in my first subscription...

**Comment by Mimetis** [comment]
One colleague has the same issue, by the way
So it comes from our company tenant. 
Do know why honestly...

**Comment by arkiaman** [comment]
You may get in touch with the App Configuration team, they should have had the same issue with the MS tenant.

I'm interested in having the reason why.

**Comment by Mimetis** [comment]
I've made a test, trying to mimic the azure auth / rest api:


Getting a token for the app conf resource (as you mentioned, and right by the way)

``` 
az account get-access-token -o json --resource https://confXXXX.azconfig.io
```
![image](https://user-images.githubusercontent.com/4592555/95077001-0d122c80-0713-11eb-9b42-31885bc51ea5.png)

From this token, I've directly made a test from Postman, using this token and trying to create a Key / Value, using this doc : https://github.com/Azure/AppConfiguration/blob/main/docs/REST/kv.md#set-key

And unfortunatelly, it worked correctly....

![image](https://user-images.githubusercontent.com/4592555/95077092-3632bd00-0713-11eb-9d71-1a85e8b9f051.png)

Hard time trying to debug this one ! :)

**Comment by arkiaman** [comment]
Damn, I don't know how to debug this issue.... I'll try to reproduce using a brand new identity.

At the beginning, your identity was only owner of the subscription right ?

**Comment by Mimetis** [comment]
I guess I need to do it on my own, since you're not able to reproduce it :)
I'm just a little bit worried about going into GO right now :)

I will stop investigate now, since I have others tasks to do urgently
Will try to keep you updated if I found something new in the next days / months

**Comment by Mimetis** [comment]
Hum,
I've tested it again on our tenant and now it's working ....
Don't know why it did not this morning, I guess something "magical" happened 👍 
Thanks for the support

**Comment by arkiaman** [comment]
I remember that the RBAC permission may take some time to be really applied

**Comment by Mimetis** [comment]
Yes, that's my assumption here

**Comment by mcblair** [comment]
I can confirm that I encountered `Forbidden` though I am owner and contributor to the target subscription. What fixed it for me was explicitly adding myself as `App Configuration Data Owner` to the subscription, and waiting ~10 minutes before applying again. The documentation states `App Configuration Data Owner` is required, but I assumed that because I was subscription owner I wouldn't need it explicitly.

Thought I would chime in for anyone who runs into this.

**Comment by Feggah** [comment]
@mcblair This is one of those things that it is good to keep in the documentation. I was exactly in this same problem and your comment saved my day, thanks!
