### ISSUE TITLE
Does not work with User Assigned Managed Identity

### ISSUE THREAD

**Issue by valakson** [arkiaconsulting/terraform-provider-akc#32]
When running on Azure VM with **user assigned** managed identity, the provider cannot read/set/delete App Config Keys.

Terraform v1.0.4
on linux_amd64
+ provider registry.terraform.io/arkiaconsulting/akc v1.1.1
+ provider registry.terraform.io/hashicorp/azurerm v2.71.0

The error is `Error: Unexpected error (Forbidden)`

When creating/reading App Configuration keys with Azure cli, it works as expected

For terraform credentials are provided through [https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/managed_service_identity#configuring-with-environment-variables] (environment variables)

For Azure cli `az login` is used:
```bash
az login --identity -u $ARM_CLIENT_ID
az appconfig kv set --endpoint https://$ENDPOINT.azconfig.io --key color --value red --auth-mode login
```

**Comment by Feggah** [comment]
Getting the same error here @valakson , when using a Service Principal/CLI authentication, even if these accounts has permissions, I receive 403 error. How did you solve this problem?

**Comment by valakson** [comment]
Running under service principal works fine for me. I assume you haven't assigned RBAC role to the SP (for data plane), see #17

**Comment by Feggah** [comment]
> Running under service principal works fine for me. I assume you haven't assigned RBAC role to the SP (for data plane), see #17

Thanks! I found the same solution in #3 , I was using Contributor role :dizzy_face:
