### ISSUE TITLE
Identity not found, when deployed from Azure devops

### ISSUE THREAD

**Issue by Mimetis** [arkiaconsulting/terraform-provider-akc#5]
I'm not done with strange behaviors :)

I've a different behavior when I'm trying to deploy from azure devops and from my machine.
To be sure I've the same rights, I'm using the same Service Principal in Devops an locally on my machine

``` 
 az account show
{
  "environmentName": "AzureCloud",
  "id": "6d854ccd-XXX",
  "tenantId": "72f988bf-86f1-41af-91ab-2d7cd011db47",
  "user": {
    "name": "88ef9e7c-XXX",
    "type": "servicePrincipal"
  }
}
```

This service principal is the one used in devops as well.
Obviously this SPN has the "owner" and "app conf contributor" role assigned.

![image](https://user-images.githubusercontent.com/4592555/95231026-ecc19b00-0802-11eb-8a62-1c0ae7cbe739.png)

Locally, everything is working fine.
In my script (the same as the last closed issue) I'm waiting a bit (180 s) to be sure everything is deployed correctly, role assignement and so on... before trying to create a key / value inside my app conf.

Eventually everything runs smoothly locally:

![image](https://user-images.githubusercontent.com/4592555/95230955-d61b4400-0802-11eb-8438-29343e4c2c38.png)

But unfortunatelly from Azure Devops i've this error raised:
![image](https://user-images.githubusercontent.com/4592555/95230836-ab30f000-0802-11eb-9cde-4dd795e6e228.png)

```
azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://confdevjlcn.azconfig.io/kv/rg_name?api-version=1.0&label=%00: StatusCode=400 
-- Original Error: adal: Refresh request failed. Status Code = '400'. 
Response body: {"error":"invalid_request","error_description":"Identity not found"}[0m

2020-10-06T16:27:38.3860725Z [0m  on main.tf line 102, in resource "akc_key_value" "rg_name":
2020-10-06T16:27:38.3861695Z  102: resource "akc_key_value" "rg_name" [4m{[0m
```

i'm going crazy with this "identity not found" issue ...

**Comment by arkiaman** [comment]
Do you execute your terraform command from within the context of the AzureCLI (AzureCLI@2 task) ?

**Comment by Mimetis** [comment]
From the [Terraform task](https://github.com/microsoft/azure-pipelines-extensions/blob/master/Extensions/Terraform/Src/Tasks/TerraformTaskV1/README.md)

**Comment by arkiaman** [comment]
I think that the problem is the same as #4. You may populate the right environment variables within your pipeline.

**Comment by Mimetis** [comment]
Hey @arkiaconsulting 
I'm sorry to admit I finally removed the akc provider, and I do it everything from a simple batch script, using the REST API
Now everything is working fine.

I don't know why It did not work with your provider. The main problem is that I have random behaviors, sometimes with issues, sometimes without, that are really hard to debug...

**Comment by arkiaman** [comment]
And I must admit that I don't why you have random behaviours... I use the provider in production till many months without any issue...

Anyway, thank you for being involved.

**Comment by Mimetis** [comment]
It's in my backlog list to improve my GO skills. :)
Maybe from that point, I will try to figure out what was the problem here

**Comment by JT-Bruch** [comment]
I'm ran into the same series of issues :/ 

I was initially using the Terraform tasks, but have basically moved to running a Bash script and that makes it work.

The kicker is that you have to do `az logout` and have BOTH ARM & Azure configs and then it works.

I suspect that the out of the box terraform tasks cause issues with the authentication. So by removing it all.. things are much happier.

```
          ls
          az logout

          export AZURE_CLIENT_ID=value
          export AZURE_SUBSCRIPTION_ID=value
          export AZURE_TENANT_ID=value
          export AZURE_CLIENT_SECRET=value

          export ARM_CLIENT_ID="value"
          export ARM_CLIENT_SECRET="value"
          export ARM_SUBSCRIPTION_ID="value"
          export ARM_TENANT_ID="value"



          echo $AZURE_CLIENT_ID
          echo $AZURE_SUBSCRIPTION_ID
          echo $AZURE_TENANT_ID
          echo $AZURE_CLIENT_SECRET

          terraform init
          terraform plan -out=tfplan -var "admin_username=$(adminuser)" -var "admin_password=$(adminpw)" -input=false
          terraform apply -auto-approve "tfplan"

```

PSA - For anyone reading this later, don't hard code your values, I just did that for testing but have refactored & removed them. :)
