### ISSUE TITLE
Resolve a vault secret

### ISSUE THREAD

**Issue by EmFl** [arkiaconsulting/terraform-provider-akc#7]
Hello,
I'm testing your provider (thank you to have developed this) and wondering if I misunderstood something or if this is the way to go. Right now, when I try to fetch a secret in app config, I end up with the vault url. However, I don't have the information of where that vault is (ie, resource group). 
This is what I came up with to get the real value in terraform but I hope there is something easier than this.

```
data "akc_key_secret" "my_secret" {
  endpoint = data.azurerm_app_configuration.example.endpoint
  key      = "mysecretkey"
}

data "azurerm_resources" "vault" {
  type = "Microsoft.KeyVault/vaults"
  name = regex("https://(?P<vault_name>.*).vault.azure.net/secrets/(?P<secret_name>.*)", data.akc_key_secret.my_secret.secret_id)["vault_name"]
}

data "azurerm_key_vault_secret" "example" {
  name         = regex("https://(?P<vault_name>.*).vault.azure.net/secrets/(?P<secret_name>.*)", data.akc_key_secret.my_secret.secret_id)["secret_name"]
  key_vault_id = data.azurerm_resources.vault.resources[0].id
}

output "realsecret" {
  value = data.azurerm_key_vault_secret.example.value
}
```

Is this the only way today ?
Thanks

**Comment by arkiaman** [comment]
To be honest, I was not sure whether to expose the secret uri or the secret itself. I preferred exposing the secret uri because the identity running the terraform may not have the policy to get this secret (the secret may be dedicated to a deployed service managed identity).
In your case, you know that you need the secret value, so the way you're describing above is the right way to go (although it's not ideal).

**Comment by EmFl** [comment]
Wouldn't the managed identity access app conf itself instead of relying on terraform to fetch the config and then get the vault to lookup the secret ?
The azure devops extension (made by Microsoft) looks up the secret and outputs a warning if it cannot access the vault. With terraform I guess this would be a hard failure.
Would adding another resource type like akc_key_secret_value or something like that be interesting ?

**Comment by arkiaman** [comment]
I do agree. This could be an enhancement. That way, we would let the consumer decide whether he needs the id or the value itself.
But as a side note, the terraform azurerm provider team is working on a App Configuration value resource. So the days of my provider are counted, and I won't invest more time.

**Comment by EmFl** [comment]
Thanks for the useful feedback. I wasn't aware there was an official resource coming though it makes a lot of sense so I understand your decision of not investing more time into this. Thanks for having made something useful for the transition phase :)
Closing this.

**Comment by arkiaman** [comment]
@EmFl You can find some piece of info here: https://github.com/terraform-providers/terraform-provider-azurerm/issues/5840
